---

- name: Downloading kubectl
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubectl
    mode: 744
    dest: /usr/bin/
    status_code:
      - 302
      - 200
      - 304
  retries: 3
  delay: 2

- name: Copying kernel module configuration file for network filter to activate iptables
  ansible.builtin.copy:
    src: sysctl.d_k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Loading configration file to modify kernel at runtime
  ansible.builtin.command: sysctl --system
