---

- name: Downloading Google cloud public signing key
  get_url:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    dest: "/usr/share/keyrings/kubernetes-archive-keyring.gpg"

- name: Adding kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Copying kernel module configuration file for network filter
  ansible.builtin.copy:
    src: modules-load.d_k8s.conf
    dest: /etc/modules-load.d/k8s.conf

- name: Copying kernel module configuration file for network filter to activate iptables
  ansible.builtin.copy:
    src: sysctl.d_k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Loading configration file to modify kernel at runtime
  ansible.builtin.command: sysctl --system

- name: Installing kubectl binary (apt)
  ansible.builtin.apt:
    name:
      - "kubectl"
    state: present

- name: Preventing kubectl from being upgraded
  dpkg_selections:
    name: kubectl
    selection: hold

- name: Ensuring that kubectl is installed
  ansible.builtin.command: dpkg -l --no-pager kubectl
  tags:
    - test
