---

- name: Removing kube-scheduler files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kube_scheduler_config_path }}/kube-scheduler.yaml"
    - "{{ kube_scheduler_config_path }}/ca.pem"
    - "{{ kube_scheduler_config_path }}/kube-scheduler.pem"
    - "{{ kube_scheduler_config_path }}/kube-scheduler-key.pem"
    - "/etc/systemd/system/kube-scheduler.service"
    - "{{ kube_scheduler_config_path }}/kube-scheduler.kubeconfig"

- name: Shutting down kube-scheduler service
  ansible.builtin.systemd:
    name: kube-scheduler
    state: stopped
