---

- name: Removing configuration and binary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/usr/local/bin/kube-scheduler"
    - "{{ kube_scheduler_config_path }}"
    - "/etc/systemd/system/kube-scheduler.service"

- name: Shutting down kube-scheduler service
  ansible.builtin.systemd:
    name: kube-scheduler
    state: stopped
