---

- name: Installing nginx and ufw
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    force: true
  with_items:
    - nginx
    - ufw

- name: Copying nginx configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - "Restart nginx service"

- name: Creating configuration directory
  ansible.builtin.file:
    path: /etc/nginx/tcpconf.d
    state: directory

- name: Copying kubernetes nginx configuration file
  ansible.builtin.template:
    src: kubernetes.conf.j2
    dest: /etc/nginx/tcpconf.d/kubernetes.conf
  notify:
    - "Restart nginx service"

- name: Enabling ufw iptables
  ansible.builtin.command: sudo ufw enable

- name: Defining iptables rules to allow nginx HTTPS inbound traffic
  ansible.builtin.command: sudo ufw allow 'Nginx HTTPS'

- name: Defining iptables rules to allow nginx SSH inbound traffic
  ansible.builtin.command: sudo ufw allow 'Nginx SSH'

- name: Ensuring nginx is installed
  ansible.builtin.command: nginx -v
  tags:
    - test

- name: Starting nginx service (systemd)
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
