---

- name: Removing nginx configuration files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/ssl/certs/kubernetes-key.pem
    - /etc/ssl/certs/kubernetes.pem

- name: Uninstalling nginx (apt)
  ansible.builtin.apt:
    name: "nginx"
    state: absent

- name: Removing unneeded dependencies
  ansible.builtin.apt:
    autoremove: true
