---

- name: Apply Yard default configuration to every targeted hosts
  hosts: home
  gather_facts: no
  become: yes
  roles:
    - common

- name: Yard cloud app platform installation using Kubernetes
  hosts: home
  become: yes
  vars:
    kubernetes_public_ip: 192.168.1.1
    cluster_name: "yard-kubernetes"
  roles:
    - docker
    - cfssl
    - k8s-kubectl
    - k8s-etcd
    - k8s-api-server
    - k8s-scheduler
    - k8s-controller-manager
