---

- name: Apply Yard default configuration to every targeted hosts
  hosts: scaleway
  gather_facts: no
  become: yes
  roles:
    - common

- name: Yard cloud app platform installation using Kubernetes
  hosts: scaleway
  become: yes
  roles:
    - docker
    - k8s
