---

- name: Provision Kubernetes cluster default configuration
  hosts: home
  gather_facts: no
  become: yes
  roles:
    - common

- name: Provision Kubernetes cluster
  hosts: home
  become: yes
  vars:
    kubernetes_public_ip: 192.168.1.1
    cluster_name: "yard-kubernetes"
  roles:
    - docker
    - k8s-kubectl
    - k8s-etcd
    - k8s-api-server
    - k8s-scheduler
    - k8s-controller-manager
