---

- name: Provisioning servers with common tools
  hosts: single-node
  gather_facts: no
  become: yes
  vars:
    playbook_mode: "install"
  roles:
    - common

- name: Provisioning Kubernetes cluster
  hosts: single-node
  become: yes
  vars:
    kubernetes_public_ip: 192.168.1.1
    cluster_name: "yard-kubernetes"
    playbook_mode: "install"
  roles:
    - docker
    - k8s-kubectl
    - k8s-etcd
    - k8s-apiserver
    - k8s-scheduler
    - k8s-controller-manager
    - k8s-worker
