---

- name: Deprovisionning Kubernetes cluster default configuration
  hosts: home
  gather_facts: no
  become: yes
  vars:
    playbook_mode: "uninstall"
  roles:
    - common
    - docker
    - k8s-api-server
    - k8s-controller-manager
    - k8s-etcd
    - k8s-kubectl
    - k8s-scheduler
