---

- name: Deprovisionning Kubernetes cluster and common tools
  hosts: home
  gather_facts: no
  become: yes
  vars:
    playbook_mode: "uninstall"
  roles:
    - common
    - docker
    - k8s-apiserver
    - k8s-controller-manager
    - k8s-etcd
    - k8s-kubectl
    - k8s-scheduler
    - k8s-worker
