---

- name: Downloading release binary
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /tmp
    mode: '0744'

- name: Unarchiving binary
  ansible.builtin.unarchive:
    src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Installing binary
  ansible.builtin.copy:
    src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64/etcd"
    dest: /usr/local/bin
    mode: '0777'
    remote_src: yes

- name: Installing etcdctl binary
  ansible.builtin.copy:
    src: "/tmp/etcd-v{{ etcd_version }}-linux-amd64/etcdctl"
    dest: /usr/local/bin
    mode: '0777'
    remote_src: yes

- name: Creating configuration directory
  ansible.builtin.file:
    path: /etc/etcd
    state: directory

- name: Creating execution directory
  ansible.builtin.file:
    path: /var/lib/etcd
    state: directory
    mode: '0744'

- name: Uploading certificate authority
  ansible.builtin.copy:
    src: "ca.pem"
    dest: /etc/etcd

- name: Uploading kubernetes certificate private key
  ansible.builtin.copy:
    src: "kubernetes-key.pem"
    dest: /etc/etcd

- name: Uploading kubernetes certificate public key
  ansible.builtin.copy:
    src: "kubernetes.pem"
    dest: /etc/etcd

- name: Uploading service unit file (systemd)
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service

- name: Starting service (systemd)
  ansible.builtin.systemd:
    name: etcd
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Waiting for the service startup
  ansible.builtin.pause:
    seconds: 5

- name: Ensuring that the etcd service is installed (etcdctl)
  ansible.builtin.command: "etcdctl member list \
  --endpoints=https://{{ ansible_host }}:2379 \
  --cacert=/etc/etcd/ca.pem \
  --cert=/etc/etcd/kubernetes.pem \
  --key=/etc/etcd/kubernetes-key.pem"
  tags:
    - test
