---

- name: Removing configuration and binary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    - /usr/local/bin/etcdctl
    - /usr/local/bin/etcd
    - /var/lib/etcd
    - /etc/etcd
    - /etc/systemd/system/etcd.service

- name: Shutting down service (systemd)
  ansible.builtin.systemd:
    name: etcd
    state: stopped
