---

- name: Restart kube-proxy service
  ansible.builtin.systemd:
    name: kube-proxy
    daemon_reload: yes
    state: restarted

- name: Restart kubelet service
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
