---

- name: Installing packages dependencies from package manager (apt)
  ansible.builtin.apt:
    name: "{{ apt_default_packages }}"
    state: present

- name: Ensuring that the packages are installed
  ansible.builtin.command: dpkg -l --no-pager "{{ item }}"
  with_items: "{{ apt_default_packages }}"
  tags:
    - test
