---

- name: Uninstalling common packages dependencies using (apt)
  ansible.builtin.apt:
    name: "{{ apt_default_packages }}"
    state: absent

- name: Removing unneeded dependencies
  ansible.builtin.apt:
    autoremove: true
