---

- name: Installing dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - conntrack
    state: present

- name: Adding apt key
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "https://download.docker.com/linux/{{ distribution }}/gpg"

- name: Adding GPG key
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ distribution }} {{ distribution_release }} stable'
    state: present
    filename: docker
    update_cache: true

- name: Creating configuration folder
  file: path="{{ configuration_folder_path }}" state=directory

- name: Adding daemon configuration file
  ansible.builtin.template:
    src: daemon.j2
    dest: "{{ configuration_folder_path }}/daemon.json"

- name: Installing docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  retries: 3
  delay: 2

- name: Downloading cri-dockerd to control Docker via Kubernetes
  ansible.builtin.get_url:
    url: https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.0/cri-dockerd-0.3.0.amd64.tgz
    dest: /tmp/

- name: Unarchiving cri-dockerd tar.gz
  ansible.builtin.unarchive:
    src: "/tmp/cri-dockerd-0.3.0.amd64.tgz"
    mode: 0755
    dest: /tmp
    remote_src: yes
    owner: root
    group: root

- name: Uploading cri-docker binary
  ansible.builtin.copy:
    src: "/tmp/cri-dockerd/cri-dockerd"
    dest: /usr/bin/cri-dockerd
    remote_src: yes

- name: Uploading cri-dockerd service configuratin file (systemd)
  ansible.builtin.template:
    src: cri-docker.service.j2
    dest: /etc/systemd/system/cri-docker.service

- name: Uploading cri-dockerd socket configuratin file (systemd)
  ansible.builtin.template:
    src: cri-docker.socket.j2
    dest: /etc/systemd/system/cri-docker.socket

- name: Restarting docker daemon
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Restarting cri-dockerd
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: cri-docker

- name: Ensuring that service is running
  ansible.builtin.command: docker info
  tags:
    - test
