---

- name: Uninstalling docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: absent

- name: Removing configuration file
  ansible.builtin.file:
    path: "{{ configuration_folder_path }}"
    state: absent

- name: Removing docker repository from apt configuration file
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ distribution }} {{ distribution_release }} stable'
    state: absent

- name: Removing cri-docker configuration files (systemd)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/cri-docker.socket
    - /etc/systemd/system/cri-docker.service

- name: Shutting down cri-docker service
  ansible.builtin.systemd:
    name: cri-docker
    state: stopped

- name: Shutting down docker service
  ansible.builtin.systemd:
    name: docker
    state: stopped
