---

- name: Downloading binary
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kube_api_server_version }}/bin/linux/amd64/kube-apiserver"
    dest: "/usr/local/bin"
    mode: '0744'

- name: Creating configuration directory
  ansible.builtin.file:
    path: /var/lib/kubernetes
    state: directory

- name: Uploading certificate authority private key
  ansible.builtin.copy:
    src: "ca-key.pem"
    dest: /var/lib/kubernetes
  notify:
    - "Restart Kubernetes API server"

- name: Uploading certificate authority public key
  ansible.builtin.copy:
    src: "ca.pem"
    dest: /var/lib/kubernetes
  notify:
    - "Restart Kubernetes API server"

- name: Uploading kubernetes API certificate private key
  ansible.builtin.copy:
    src: "kubernetes-key.pem"
    dest: /var/lib/kubernetes
  notify:
    - "Restart Kubernetes API server"

- name: Uploading kubernetes API certificate public key
  ansible.builtin.copy:
    src: "kubernetes.pem"
    dest: /var/lib/kubernetes
  notify:
    - "Restart Kubernetes API server"

- name: Uploading service account certificate private key
  ansible.builtin.copy:
    src: "service-account-key.pem"
    dest: /var/lib/kubernetes
  notify:
    - "Restart Kubernetes API server"

- name: Uploading service account certificate public key
  ansible.builtin.copy:
    src: "service-account.pem"
    dest: /var/lib/kubernetes
  notify:
    - "Restart Kubernetes API server"

- name: Uploading encryption config yaml
  ansible.builtin.copy:
    src: "encryption-config.yaml"
    dest: /var/lib/kubernetes
  notify:
    - "Restart Kubernetes API server"

- name: Uploading service unit (systemd)
  ansible.builtin.template:
    src: kube-apiserver.j2
    dest: /etc/systemd/system/kube-apiserver.service
  notify:
    - "Restart Kubernetes API server"

- name: Starting service
  ansible.builtin.systemd:
    name: kube-apiserver
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Ensure service is running GET - /livez
  ansible.builtin.command: curl --cacert /var/lib/kubernetes/ca.pem https://192.168.1.50:6443/livez
