---

- name: Removing kube-controller-manager files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/kube-controller-manager
    - /var/lib/kubernetes/ca.pem
    - /var/lib/kubernetes/ca-key.pem
    - /var/lib/kubernetes/kube-controller-manager-key.pem
    - /var/lib/kubernetes/kube-controller-manager.pem
    - /var/lib/kubernetes/service-account-key.pem
    - "{{ kube_controller_manager_config_path }}/kube-controller-manager.kubeconfig"
    - /etc/systemd/system/kube-controller-manager.service

- name: Shutting down kube-controller-manager service
  ansible.builtin.systemd:
    name: kube-controller-manager
    state: stopped
